### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by fei1234** [liuzhongning/NNSlideTitleView#1]
建议添加一个功能：可以设定选择了第几个btn，从而来更新UI. (有的时候，需要做滑动下面的内容，来改变SlideTitleView的位置的需求)。

**Comment by liuzhongning** [comment]
您好! 感谢建议! 不过项目里面写的有, 当你设置属性 selectedTag 时, 会有这样的效果, 例如:
`titleView.selectedTag = 2;`
会自动选中 tag 为 2 的按钮;
